pipeline {
    agent any
    // Poll the SCM every 5 minutes
    triggers {
        pollSCM('H/5 * * * *') 
    }
    
    environment {
        // Defining the environment for Python virtual environment
        VENV_DIR = 'bitezy_env'
    }
    
    stages {
        stage('Checkout') {
            steps {
                // Checkout the code from the specified repository and branch
                // Specify your own repository and branch
                git url: 'https://github.com/karthikkgunasekaran/ace_bitezy', branch: 'main'
            }
        }
        
        stage('Install Dependencies and Run Tests') {
            steps {
                script {
                    sh '''
                        python3 -m venv ${VENV_DIR}
                        source ${VENV_DIR}/bin/activate
                        pip3 install -r requirements.txt
                        ${VENV_DIR}/bin/pytest src/tests/
                        deactivate
                    '''
                }
            }
        }
    }
    
    post {
        success {
            echo 'Build and tests passed successfully!'
        }
        failure {
            echo 'Build or tests failed.'
        }
    }
}